name: Build, Deploy, Update PR

on:
  push:
    branches:
      - staging

jobs:
  auto-pull-request:
    name: Create/Update PR to Master
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_TITLE: "Staging Changes"
          PULL_REQUEST_BODY: "Automated PR to merge changes to production from staging"
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV: production # readonly production data in sandbox
      REACT_APP_FIREBASE_API_KEY:  ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
      REACT_APP_AUTH_DOMAIN:  ${{ secrets.REACT_APP_AUTH_DOMAIN }} 
      REACT_APP_DATABASE_URL:  ${{ secrets.REACT_APP_DATABASE_URL }} 
      REACT_APP_PROJECT_ID:  ${{ secrets.REACT_APP_PROJECT_ID }} 
      REACT_APP_STORAGE_BUCKET:  ${{ secrets.REACT_APP_STORAGE_BUCKET }} 
      REACT_APP_MESSENGER_SENDER_ID:  ${{ secrets.REACT_APP_MESSENGER_SENDER_ID }} 
      REACT_APP_APP_ID:  ${{ secrets.REACT_APP_ID }} 
      REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }} 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Use sandbox project
        uses: w9jds/firebase-action@master
        with:
          args: use alec-ng-sandbox
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set Firebase hosting deploy target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting sbx-site alec-ng-sandbox
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:sbx-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
