name: Build and Deploy

on:
  push:
    branches:
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      REACT_APP_ENV: sandbox # readonly production data in sandbox
      REACT_APP_SBX_FIREBASE_API_KEY:  ${{ secrets.REACT_APP_SBX_FIREBASE_API_KEY }}
      REACT_APP_SBX_AUTH_DOMAIN:  ${{ secrets.REACT_APP_SBX_AUTH_DOMAIN }} 
      REACT_APP_SBX_DATABASE_URL:  ${{ secrets.REACT_APP_SBX_DATABASE_URL }} 
      REACT_APP_SBX_PROJECT_ID:  ${{ secrets.REACT_APP_SBX_PROJECT_ID }} 
      REACT_APP_SBX_STORAGE_BUCKET:  ${{ secrets.REACT_APP_SBX_STORAGE_BUCKET }} 
      REACT_APP_SBX_MESSENGER_SENDER_ID:  ${{ secrets.REACT_APP_SBX_MESSENGER_SENDER_ID }} 
      REACT_APP_SBX_APP_ID:  ${{ secrets.REACT_APP_SBX_APP_ID }} 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Use sandbox project
        uses: w9jds/firebase-action@master
        with:
          args: use alec-ng-sandbox
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set Firebase hosting deploy target
        uses: w9jds/firebase-action@master
        with:
          args: target:apply hosting sbx-site alec-ng-sandbox
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:sbx-site
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
